// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGNRWsrXkvTFLWOZewBDphU8khvgmqIs',
    appId: '1:542855788026:web:4b730219f01940e10e6043',
    messagingSenderId: '542855788026',
    projectId: 'fluttertextdb',
    authDomain: 'fluttertextdb.firebaseapp.com',
    databaseURL: 'https://fluttertextdb-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertextdb.appspot.com',
    measurementId: 'G-F31KE6ZLGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzuIMrKdiWa0RuFYbMmysckxgR823Z4Ec',
    appId: '1:542855788026:android:1a85b64393d928090e6043',
    messagingSenderId: '542855788026',
    projectId: 'fluttertextdb',
    databaseURL: 'https://fluttertextdb-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertextdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdnTpe35DufR18Em8UafOM_0hDSB-FMPU',
    appId: '1:542855788026:ios:6936355a2a802fcb0e6043',
    messagingSenderId: '542855788026',
    projectId: 'fluttertextdb',
    databaseURL: 'https://fluttertextdb-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertextdb.appspot.com',
    iosBundleId: 'com.amit.viva',
  );
}
